name: Build (Windows, MSVC)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4    
    - uses: humbletim/install-vulkan-sdk@v1.2
      with:
        cache: true        
    - uses: jurplel/install-qt-action@v4.2.1
      with: 
        version: 6.8.3
        cache: true

    - name: Replace libien ref
      run: sed -i -e 's/ien646\/libien/ien646\/libien-mirror/g' "${{github.workspace}}/cmake/dependencies.cmake"
      shell: bash        

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}